
services:
  bot:
    image: python:3.9
    container_name: python_bot
    working_dir: /usr/src/app
    links:
      - "mongodb:mongo"
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - mongodb
    command: sh -c "pip install -r requirements.txt && python -u main.py"
    restart: unless-stopped

  mongodb:
    image: 'mongo:4.4.6'
    volumes:
      - 'mongo-data:/data/db'
    restart: unless-stopped

volumes:
  mongo-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.data
